export const commentsConst = {
  GET_COMMENTS: "GET_COMMENTS",
  GET_COMMENTS_SUCCESS: "GET_COMMENTS_SUCCESS",
  ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
  DELETE_COMMENT_SUCCESS: "DELETE_COMMENT_SUCCESS",
  EDIT_COMMENT_SUCCESS: "EDIT_COMMENT_SUCCESS",
  VOTE_COMMENT_SUCCESS: "VOTE_COMMENT_SUCCESS",
};
