export const postsConst = {
  GET_ALL_POSTS: "GET_ALL_POSTS",
  GET_ALL_POSTS_SUCCESS: "GET_ALL_POSTS_SUCCESS",
  VOTE: "VOTE",
  GET_POST_DETAIL: "GET_POST_DETAIL",
  GET_ALL_POST_DETAIL_SUCCESS: "GET_ALL_POST_DETAIL_SUCCESS",
  ADD_NEW_POST: "ADD_NEW_POST",
  ADD_NEW_POST_SUCCESS: "ADD_NEW_POST_SUCCESS",
  DELETE_POST: "DELETE_POST",
  EDIT_POST_SUCCESS: "EDIT_POST_SUCCESS",
};
